### ISSUE TITLE
Missing "Home" Option in the Navbar

### ISSUE THREAD

**Issue by neeru24** [Abhay-hack/Lumina#25]
Missing "Home" Option in the Navbar

**Current Behavior:**
The website's navigation bar does not include a direct "Home" option, making it inconvenient for users to return to the homepage when browsing other sections of the site. Users currently have to rely on the logo or manually navigate back.

**Proposed Improvement:**
Add a "Home" option to the navbar that links directly to the homepage (index.html). This will enhance navigation and provide a clear and consistent way for users to return to the main page.

![image](https://github.com/user-attachments/assets/7243f669-b1df-48cd-9d3e-ca05e908c0df)

**Comment by Abhay-hack** [comment]
It is already assigned to other person.
